### ISSUE TITLE
Monad dependency fail

### ISSUE THREAD

**Issue by aratz-lasa** [multiformats/ex_multihash#11]
I let you know that this library fails to compile because its `Monad` depency fails:

`== Compilation error in file lib/monad.ex ==
** (SyntaxError) lib/monad.ex:247: reserved token: __block__
    (elixir) lib/kernel/parallel_compiler.ex:229: anonymous fn/4 in Kernel.ParallelCompiler.spawn_workers/7`

**Comment by zabirauf** [comment]
Thanks for reporting the issue. I'll try to repro.

**Comment by zabirauf** [comment]
I tried a rebuild on travis and it was [successful](https://travis-ci.com/multiformats/ex_multihash/builds/141346241). Can you please give information on your version of elixir, erlang and ex_multihash version you are using.

**Comment by aratz-lasa** [comment]
Oh yes I'm sorry:
- Multihash version: `1.0.0`
- Elixir version: `1.9.4`
- Erlang version: `22`

**Comment by xprazak2** [comment]
I run into similar problems today with monad 1.0, it seems to be fixed in 2.0.

**Comment by rvagg** [comment]
closing due to inactivity, archiving repo
